site_name: Django Subforms
site_description: "Wrap django forms as fields and fields as dynamic arrays."

nav:
  - Home: index.md
  - Example: example.md

theme:
  name: readthedocs
  highlightjs: false  # Use pygments instead.

exclude_docs: |
  *.py
  snippets/*

markdown_extensions:
  pymdownx.highlight:
    anchor_linenums: true
    linenums: true
  pymdownx.inlinehilite:
  pymdownx.blocks.details:
  pymdownx.snippets:
    base_path: docs/snippets
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:mermaid2.fence_mermaid
  toc:
    permalink: 🔗
  attr_list:
  meta:

plugins:
  - search:
  - mermaid2:
      version: 10.2.4

extra_css:
  - css/docs.css
  - css/pygments.css
